name: Production deploy to Amazon S3
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.2.0
      uses: actions/setup-node@v1
      with:
        node-version: 14.2.0
    - name: Yarn install
      run: yarn install
    - name: Build for production
      run: yarn run build  
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - uses: badsyntax/github-action-aws-s3@v0.0.1
      name: Sync HTML files to S3
      id: sync-s3
      with:
        bucket: ${{ secrets.AWS_S3_BUCKET }}
        aws-region: 'us-east-1'
        action: 'sync' # sync|clean
        src-dir: 'build' # required only if action is sync
        files-glob: '**/*' # required only if action is sync
        sync-strategy: |
          ETag
          Content-Type
          Cache-Control              
    - name: Invalidate Cloudfront
      uses: chetan/invalidate-cloudfront-action@master
      env:
        DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
        PATHS: '/*'
        AWS_REGION: 'us-east-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}